# Use an official Go image as the build environment
FROM golang:1.23

# Set the working directory inside the container
WORKDIR /app

# Install Air for hot reloading
RUN go install github.com/air-verse/air@latest

# Copy the .air.toml configuration file
COPY config/.air.toml /app/config/.air.toml

# Copy the go.mod and go.sum files first
COPY go.mod go.sum ./
RUN go mod download

# Copy the application source code
COPY main.go .
COPY backend/ ./backend/
COPY config/certs/ca.crt /config/ca.crt
COPY frontend /app/frontend

# Expose the application port
EXPOSE 8080

# Command to run Air with the correct path
CMD ["air", "-c", "/app/config/.air.toml"]
