# Use a minimal Go runtime image
FROM debian:bullseye-slim

# Copy the binary from the local build context to the container
WORKDIR /app
COPY backend /app/backend

# Expose the port used by the Go backend
EXPOSE 8080

# Run the Go server binary
CMD ["/app/backend"]
